spring:
  application:
    name: devassistant

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_dev_assistant
    username: ai_user
    password: ai_password

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    anthropic:
      api-key: {{ANTRHOPIC_API_KEY}}
      chat:
        options:
          model: claude-sonnet-4-6
          temperature: 0.2
          max-tokens: 300
  data:
    redis:
          host: localhost
          port: 6379


server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        failure-rate-threshold: 50
        sliding-window-size: 5
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s

logging:
  level:
    root: INFO